application: sharkattackdata
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

libraries:
 - name: webapp2
   version: latest
 - name: jinja2
   version: latest

handlers:
- url: /favicon.ico
  static_files: assets/images/favicon.ico
  upload: assets/images/favicon.ico
- url: /serviceops/.*
  script: sharkattackdata.application
  login: admin
- url: /.*
  script: sharkattackdata.application
