application: sharkattackdata
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

libraries:
 - name: webapp2
   version: latest
 - name: jinja2
   version: latest

handlers:
- url: /.*
  script: sharkattackdata.application
